live_config_reload: true
draw_bold_text_with_bright_colors: false

window:
  dimensions:
    columns: 80
    lines: 30
  padding:
    x: 0
    y: 0
  opacity: 0.92
  title: Terminal
  dynamic_title: false
  dynamic_padding: true

scrolling:
  history: 4000

font:
  normal:
    family: JetBrains Mono NL
  size: 12.0
  builtin_box_drawing: false

colors:
  primary:
    foreground: '#f4e5bf'
    background: '#1d2021'
  normal:
    black:    '#303536'
    red:      '#d83e33'
    green:    '#8ac87d'
    yellow:   '#f2ba41'
    blue:     '#81aece'
    cyan:     '#7ec9b1'
    magenta:  '#cda2e3'
    white:    '#fcf8ee'
  bright:
    black:    '#303536'
    red:      '#d83e33'
    green:    '#8ac87d'
    yellow:   '#f2ba41'
    blue:     '#81aece'
    cyan:     '#7ec9b1'
    magenta:  '#cda2e3'
    white:    '#fcf8ee'

cursor:
  style:
    shape: Block
    blinking: Off
  unfocused_hollow: true
  thickness: 0.10

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

key_bindings:
  - { key: N,              mods: Shift|Control,          action: SpawnNewInstance      }
