live_config_reload: true

# env:
#   TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 30
  padding:
    x: 0
    y: 0
  opacity: 0.90
  dynamic_title: true
  dynamic_padding: true

scrolling:
  history: 4000

font:
  normal:
    family: JetBrains Mono
    style: Regular
  size: 11.0
  builtin_box_drawing: false

colors:
  primary:
    background: '#1e1e1e'
    foreground: '#d4d4d4'
  normal:
    black:   '#2f2f2f'
    red:     '#dd3838'
    green:   '#7c9b43'
    yellow:  '#edb335'
    blue:    '#5197d0'
    cyan:    '#4ec9a7'
    magenta: '#d073c9'
    white:   '#dcdcdc'
  bright:
    black:   '#4c4c4c'
    red:     '#ef7f70'
    green:   '#b0ce8c'
    yellow:  '#dfd27f'
    blue:    '#65bceb'
    cyan:    '#89decd'
    magenta: '#c586c0'
    white:   '#f3f3f3'

cursor:
  style:
    shape: Block
    blinking: Off
  unfocused_hollow: true
  thickness: 0.10

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
