icons_format     = "{icon}"
invert_scrolling = false

[theme]
theme = "native"

[icons]
icons = "none"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "$layout"
[block.mappings]
"English (US)" = "EN"
"Portuguese (Brazil)" = "BR"

# Memory
# [[block]]
# block = "memory"
# format = "MEM:$mem_total_used_percents.eng(w:2) "

# Battery
[[block]]
block = "battery"
format = "[$percentage]"
full_format = "[$percentage]"
empty_format = "![$percentage]"
missing_format = ""
empty_threshold = 10
full_threshold = 95

# Sound
[[block]]
block = "sound"
format = "V:{$volume.eng(w:2) |mute}"
max_vol = 100
[[block.click]]
button = "left"
action = "toggle_mute"
[[block.click]]
button = "right"
cmd    = "pavucontrol-qt"

# Date
[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%b %d(%a) %H:%M') "

