icons_format = "{icon}"
invert_scrolling = true

[theme]
theme = "native"

[icons]
icons = "none"

# Memory
# [[block]]
# block = "memory"
# format = "MEM:$mem_total_used_percents.eng(w:2) "

# Battery
[[block]]
block = "battery"
format = "[$percentage]"
missing_format = ""

# [[block]]
# block = "backlight"
# device = "/sys/class/backlight/intel_backlight"
# format = "* $brightness"

# Sound
[[block]]
block = "sound"
format = "V:{$volume.eng(w:2) |mute}"
max_vol = 100
[[block.click]]
button = "left"
action = "toggle_mute"
[[block.click]]
button = "right"
cmd    = "pavucontrol-qt"

# Date
[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%b %d(%a) %H:%M') "
