#!/bin/sh

# Wayland is notoriously retarded with keyboard layouts, leaving
# everything for the compositor to handle. This only works for Sway

input_devs='12815:20508:SONiX_USB_Keyboard_System_Control'

Run() { echo "$@"; $@; }

for dev in $input_devs; do
	echo $dev
	Run swaymsg input $dev xkb_switch_layout next
	Run swaymsg input $dev xkb_options caps:swapescape
done
