#!/bin/sh

cd "$HOME/.config/river"
lua init.lua | sh

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

# for mode in normal locked; do
#     # Eject the optical drive (well if you still have one that is)
#     riverctl map $mode None XF86Eject spawn 'eject -T'
#
#     # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
#     riverctl map $mode None XF86AudioRaiseVolume  spawn 'volume up  5'
#     riverctl map $mode None XF86AudioLowerVolume  spawn 'volume dwn 5'
#     riverctl map $mode None XF86AudioMute         spawn 'volume mute'
#
#     # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
#     riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
#     riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
#
#     # Control screen backlight brightness with light (https://github.com/haikarainen/light)
#     riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
#     riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
# done
#
# # Enable touchpad tap-to-click
# riverctl input pointer-10248-257-MSFT0001:01_2808:0101_Touchpad tap enabled
#
# # Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"
#
# # Set app-ids and titles of views which should use client side decorations
# # riverctl csd-filter-add app-id "gedit"
#
# # Set the default layout generator to be rivertile and start it.
# # River will send the process group of the init executable SIGTERM on exit.
# riverctl default-layout rivertile
#
# # Start layout program
# rivertile -outer-padding 2 -view-padding 0 &
#
# # Start bg program
# swaybg -i ~/pics/leaves_dark.jpg &
# # Start statusbar
# i3bar-river &
#
